set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

set_property PACKAGE_PIN F4 [get_ports ps2c]
set_property PACKAGE_PIN B2 [get_ports ps2d]
set_property IOSTANDARD LVCMOS33 [get_ports ps2c]
set_property IOSTANDARD LVCMOS33 [get_ports ps2d]


set_property IOSTANDARD LVCMOS33 [get_ports audioEn]
set_property IOSTANDARD LVCMOS33 [get_ports audioOut]
set_property PACKAGE_PIN D12 [get_ports audioEn]
set_property PACKAGE_PIN A11 [get_ports audioOut]

set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports AN4]
set_property IOSTANDARD LVCMOS33 [get_ports AN5]
set_property IOSTANDARD LVCMOS33 [get_ports AN6]
set_property IOSTANDARD LVCMOS33 [get_ports AN7]
set_property PACKAGE_PIN T10 [get_ports CA]
set_property PACKAGE_PIN R10 [get_ports CB]
set_property PACKAGE_PIN K16 [get_ports CC]
set_property PACKAGE_PIN K13 [get_ports CD]
set_property PACKAGE_PIN P15 [get_ports CE]
set_property PACKAGE_PIN T11 [get_ports CF]
set_property PACKAGE_PIN L18 [get_ports CG]
set_property PACKAGE_PIN J17 [get_ports AN0]
set_property PACKAGE_PIN J18 [get_ports AN1]
set_property PACKAGE_PIN T9 [get_ports AN2]
set_property PACKAGE_PIN J14 [get_ports AN3]
set_property PACKAGE_PIN P14 [get_ports AN4]
set_property PACKAGE_PIN T14 [get_ports AN5]
set_property PACKAGE_PIN K2 [get_ports AN6]
set_property PACKAGE_PIN U13 [get_ports AN7]
