# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/Strum/Strum.runs/synth_1/.Xil/Vivado-5012-DESKTOP-IVKJU52/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {{C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum}} {
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/PWMSerializer.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/RAM.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/RAM_image.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/VGATimingGenerator.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/Wrapper.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/alu.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/bitwise_AND.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/bitwise_OR.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/booth_mult.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/csa_32_bit.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/dffe_ref.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/eight_bit_cla.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/gp.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/left_barrel_shifter.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/mult_control.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/multdiv.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/mux_2.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/mux_4.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/mux_8.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/one_hot_decoder.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/processor.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/ps2_rx.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/reg_32.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/reg_64.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/reg_65.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/regfile.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/restoring_div.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/right_barrel_shifter.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/rng.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/six_bit_counter.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/tsb_32.v}
      {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/VGAController.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/Strum/Strum.runs/synth_1/.Xil/Vivado-5012-DESKTOP-IVKJU52/realtime/VGAController_synth.xdc}}
    rt::sdcChecksum
    set rt::top VGAController
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/Strum/Strum.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/caryp/Desktop/Important Shit/ECE350/Final Project/strum/strum/Strum/Strum.runs/synth_1/.Xil/Vivado-5012-DESKTOP-IVKJU52/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
